### PR TITLE
Fix issues running on Magento 2.4.5-p2

### PR DESCRIPTION
**Pull request by ssx**

### CODE REVIEW

**Comment by ssx** [comment]
Your extension is currently a dumpster fire on 2.4.5-p2:

```html
<style>.highlighted { background-color: #DFF7FF!important; }</style>
<form action="https://test.local/admin/admin/system_config/save/key/a0284b348457a5e5cd5f25aa1d80a10b980f3c32a823185aeb04cb14d1294c07/section/salesfire/store/1/" method="post" id="config-edit-form"
      enctype="multipart/form-data">
    <div><input name="form_key" type="hidden" value="Q02os4820fLflbK9" /></div>
    <div class="accordion">
        
<div class="entry-edit form-inline">
    Error: Call to a member function renderEventListenerAsTag() on null in /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Field.php:135
Stack trace:
#0 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Field.php(81): Magento\Config\Block\System\Config\Form\Field->_renderInheritCheckbox(Object(Magento\Framework\Data\Form\Element\Text))
#1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Block\System\Config\Form\Field->render(Object(Magento\Framework\Data\Form\Element\Text))
#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Salesfire\Salesfire\Block\Adminhtml\FeedUrl\Interceptor->___callParent('render', Array)
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Salesfire\Salesfire\Block\Adminhtml\FeedUrl\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\Data\Form\Element\Text))
#4 /var/www/html/generated/code/Salesfire/Salesfire/Block/Adminhtml/FeedUrl/Interceptor.php(23): Salesfire\Salesfire\Block\Adminhtml\FeedUrl\Interceptor->___callPlugins('render', Array, Array)
#5 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(541): Salesfire\Salesfire\Block\Adminhtml\FeedUrl\Interceptor->render(Object(Magento\Framework\Data\Form\Element\Text))
#6 /var/www/html/vendor/magento/framework/Data/Form/Element/Text.php(41): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#7 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(555): Magento\Framework\Data\Form\Element\Text->getHtml()
#8 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(98): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#9 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(76): Magento\Config\Block\System\Config\Form\Fieldset->_getChildrenElementsHtml(Object(Magento\Framework\Data\Form\Element\Fieldset\Interceptor))
#10 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(541): Magento\Config\Block\System\Config\Form\Fieldset->render(Object(Magento\Framework\Data\Form\Element\Fieldset\Interceptor))
#11 /var/www/html/generated/code/Magento/Framework/Data/Form/Element/Fieldset/Interceptor.php(338): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#12 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(555): Magento\Framework\Data\Form\Element\Fieldset\Interceptor->getHtml()
#13 /var/www/html/generated/code/Magento/Framework/Data/Form/Element/Fieldset/Interceptor.php(347): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#14 /var/www/html/vendor/magento/framework/Data/Form.php(373): Magento\Framework\Data\Form\Element\Fieldset\Interceptor->toHtml()
#15 /var/www/html/vendor/magento/framework/Data/Form.php(390): Magento\Framework\Data\Form->toHtml()
#16 /var/www/html/vendor/magento/module-backend/Block/Widget/Form.php(113): Magento\Framework\Data\Form->getHtml()
#17 /var/www/html/generated/code/Magento/Config/Block/System/Config/Form/Interceptor.php(158): Magento\Backend\Block\Widget\Form->getFormHtml()
#18 /var/www/html/vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml(13): Magento\Config\Block\System\Config\Form\Interceptor->getFormHtml()
#19 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Form\Interceptor), '/var/www/html/v...', Array)
#21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Config\Block\System\Config\Form\Interceptor), '/var/www/html/v...', Array)
#23 /var/www/html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, Array)
#24 /var/www/html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Magento\Config\Block\System\Config\Form\Interceptor), '/var/www/html/v...', Array)
#25 /var/www/html/generated/code/Magento/Config/Block/System/Config/Form/Interceptor.php(311): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#26 /var/www/html/vendor/magento/framework/View/Element/Template.php(293): Magento\Config\Block\System\Config\Form\Interceptor->fetchView('/var/www/html/v...')
#27 /var/www/html/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#28 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#29 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#30 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#31 /var/www/html/generated/code/Magento/Config/Block/System/Config/Form/Interceptor.php(536): Magento\Framework\View\Element\AbstractBlock->toHtml()
#32 /var/www/html/vendor/magento/framework/View/Layout.php(578): Magento\Config\Block\System\Config\Form\Interceptor->toHtml()
#33 /var/www/html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#34 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#35 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#36 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#37 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#38 /var/www/html/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(32): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#39 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#40 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/var/www/html/v...', Array)
#41 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#42 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Config\Block\System\Config\Edit), '/var/www/html/v...', Array)
#43 /var/www/html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, Array)
#44 /var/www/html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Magento\Config\Block\System\Config\Edit), '/var/www/html/v...', Array)
#45 /var/www/html/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#46 /var/www/html/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#47 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#48 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#49 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#50 /var/www/html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#51 /var/www/html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#52 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#53 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#54 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('system.config.e...', false)
#55 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...', false)
#56 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('content', false)
#57 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('content')
#58 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#59 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('content', false)
#60 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#61 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...', false)
#62 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#63 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#64 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('admin.scope.col...', false)
#65 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...', false)
#66 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main.col', false)
#67 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#68 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#69 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('main.col', false)
#70 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('main.col', false)
#71 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
#72 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#73 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#74 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#75 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...', false)
#76 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.content', false)
#77 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#78 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#79 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('page.content', false)
#80 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('page.content', false)
#81 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#82 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#83 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#84 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#85 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#86 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#87 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#88 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#89 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('backend.page', false)
#90 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page', false)
#91 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
#92 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('root')
#93 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#94 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('root', true)
#95 /var/www/html/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#96 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout->getOutput()
#97 /var/www/html/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#98 /var/www/html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#99 /var/www/html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(140): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#100 /var/www/html/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#101 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#102 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#103 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#104 {main}```

**Comment by ssx** [comment]
@elliotlings @alexhiggins ping.

**Comment by StephenHonor** [comment]
Thank you for the help @ssx, its always appreciated!

I just thought I would check, would these changes be php 7 safe?

**Comment by ssx** [comment]
> Thank you for the help @ssx, its always appreciated!
> 
> I just thought I would check, would these changes be php 7 safe?


@StephenHonor yes, both PHP7 & PHP8.

**Review by StephenHonor — APPROVED** [review]

**Pull request merged**
